### ISSUE TITLE
Supported PHP and MySQL versions

### ISSUE THREAD

**Issue by cyanogenic** [OpenPrinting/foomatic-db-webapp#7]
Hi,
I found some issues when deploying my own site. And I want to know what is the supported PHP and MySQL version.
Thanks.

**Comment by dheeraj135** [comment]
Hey @cyanogenic, the website is hosted on Ubuntu 12.04. The apache2, PHP and MySql are of the latest versions  supported on Ubuntu 12.04.

**Comment by cyanogenic** [comment]
> Hey @cyanogenic, the website is hosted on Ubuntu 12.04. The apache2, PHP and MySql are of the latest versions  supported on Ubuntu 12.04. 

Thanks a lot
